### ISSUE TITLE
Unexpected call of `onClick$` event on `button` element when `disabled={true}` [🐞]

### ISSUE THREAD

**Issue by MiguelValdez-mv** [BuilderIO/qwik#2267]
### Which component is affected?

Qwik Runtime

### Describe the bug

Starting from the following example:

```
export const CustomText = component$(() => (
   <span>
     <Slot />
   <span>
))

export default component$(() => (
   <>
     <button disabled onClick$={() => console.log("Test 1")}>
       Quiz 1
     </button>

     <button disabled onClick$={() => console.log("Test 2")}>
       <CustomText> Test 2 <CustomText>
     </button>
   </>
))
```
You have that when pressing the `Test 1` button the `onClick$` event does not occur, because `disabled={true}`, which is fine. However, pressing the `Test 2` button displays the `Test 2` console because that button's `onClick$` event is called despite `disabled={true}` which should not happen.

### Reproduction

https://stackblitz.com/edit/qwik-starter-e5zbny?file=src/root.tsx

### Steps to reproduce

Execute `npm run start`

### System Info

```shell
System:
    OS: Linux 5.11 elementary OS 6.1 Jólnir
    CPU: (12) x64 AMD Ryzen 5 5500U with Radeon Graphics
    Memory: 2.81 GB / 7.12 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Chromium: 107.0.5304.110
```

**Comment by nnelgxorz** [comment]
Just tried to reproduce this on the playground and it seems to work correctly. This may already be fixed in latest?

[Playground example](
https://qwik.builder.io/playground#version=0.15.0&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCY29tcG9uZW50JTI0JTJDJTIwU2xvdCU3RCUyMGZyb20lMjAlNUMlMjIlNDBidWlsZGVyLmlvJTJGcXdpayU1QyUyMiUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBDdXN0b21UZXh0JTIwJTNEJTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwKCU1Q24lMjAlMjAlMjAlM0NzcGFuJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUzQ1Nsb3QlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTNDJTJGc3BhbiUzRSU1Q24pKSU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGNvbXBvbmVudCUyNCgoKSUyMCUzRCUzRSUyMCglNUNuJTIwJTIwJTIwJTNDJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUzQ2J1dHRvbiUyMGRpc2FibGVkJTIwb25DbGljayUyNCUzRCU3QigpJTIwJTNEJTNFJTIwY29uc29sZS5sb2coJTVDJTIyVGVzdCUyMDElNUMlMjIpJTdEJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMFRlc3QlMjAxJTVDbiUyMCUyMCUyMCUyMCUyMCUzQyUyRmJ1dHRvbiUzRSU1Q24lNUNuJTIwJTIwJTIwJTIwJTIwJTNDYnV0dG9uJTIwZGlzYWJsZWQlMjBvbkNsaWNrJTI0JTNEJTdCKCklMjAlM0QlM0UlMjBjb25zb2xlLmxvZyglNUMlMjJUZXN0JTIwMiU1QyUyMiklN0QlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDQ3VzdG9tVGV4dCUzRSUyMFRlc3QlMjAyJTIwJTNDJTJGQ3VzdG9tVGV4dCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlM0MlMkZidXR0b24lM0UlNUNuJTIwJTIwJTIwJTNDJTJGJTNFJTVDbikpJTVDbiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZlbnRyeS5zZXJ2ZXIudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHJlbmRlclRvU3RyaW5nJTJDJTIwUmVuZGVyT3B0aW9ucyUyMCU3RCUyMGZyb20lMjAnJTQwYnVpbGRlci5pbyUyRnF3aWslMkZzZXJ2ZXInJTNCJTVDbmltcG9ydCUyMCU3QiUyMFJvb3QlMjAlN0QlMjBmcm9tJTIwJy4lMkZyb290JyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwKG9wdHMlM0ElMjBSZW5kZXJPcHRpb25zKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjByZW5kZXJUb1N0cmluZyglM0NSb290JTIwJTJGJTNFJTJDJTIwb3B0cyklM0IlNUNuJTdEJTVDbiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZyb290LnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBBcHAlMjBmcm9tJTIwJy4lMkZhcHAnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMFJvb3QlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQ2h0bWwlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0N0aXRsZSUzRUhlbGxvJTIwUXdpayUzQyUyRnRpdGxlJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmhlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NBcHAlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkZodG1sJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEJTNCJTVDbiUyMiU3RCU1RA%3D%3D)

**Comment by MiguelValdez-mv** [comment]
@nnelgxorz I just checked and the error still exists

![CPT2212070954-1610x661](https://user-images.githubusercontent.com/52060271/206198263-020eb30f-bab7-4d80-ab9e-2d60f9b0206c.gif)

**Comment by MiguelValdez-mv** [comment]
@nnelgxorz I just checked and the error still exists

Here is a 20 second video showing the error: https://www.loom.com/share/0589e14c271a4c22bee0733051684ab6

**Comment by deadenddeveloper** [comment]
Hi everyone,

just accidentally faced the same problem. Clicking on subnode of disabled button is not prevented.
Found one fast crutch-solution, maybe it helps someone:

```js
const btnHandler = $((event: MouseEvent) => {
    if (!(event.target as Element)?.closest("button")?.disabled) {
      // do something
    }
  });
```
