### ISSUE TITLE
[🐞] Router URL does not change when compiled as SSG

### ISSUE THREAD

**Issue by ngfelixl** [BuilderIO/qwik#3142]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When I compile the App as SSG (using the Static site (.html)) adapter it does not update the URL on route change. It works only for the dev environment and for the compiled output with JavaScript disabled. When I run a webserver and serve the compiled output without disabling JavaScript it won't update the URL.

In my app and in the reproduction app I only use the Link component exported by qwik-city.

In the provided reproduction (which is the unmodified CLI created qwik app) I would expect that it updates the URL in all cases.

For example:

- from `http://127.0.0.1:5173` to `http://127.0.0.1:5173/todolist` when I got routed after clicking on the "TODO demo" button
- from `http://127.0.0.1:5173` to `http://127.0.0.1:5173/flower` when I got routed after clicking on the "Blow my mind" button

It also did not work as expected for the versions 0.18.1 for Qwik and 0.2.1 for Qwik-City.

### Reproduction

https://github.com/ngfelixl/qwik-routing-reproduction

### Steps to reproduce

- `npm create qwik@latest` (Let's create a Qwik App (v0.19.2)
- `npm run qwik add` and select "Adapter: Static site (.html files)
- `npm run build`

Running as

- `npm start` (1)
- `npx http-server ./dist` or deploy ./dist folder output on Vercel (2)

Then

- Click on one of the bottom buttons and watch the URL
- 1 the URL updates
- 2 the URL does not update

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1 Pro
    Memory: 730.95 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    npm: 8.16.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Safari: 15.4
  npmPackages:
    @builder.io/qwik: 0.19.2 => 0.19.2 
    @builder.io/qwik-city: 0.4.0 => 0.4.0 
    undici: 5.20.0 => 5.20.0 
    vite: 4.1.4 => 4.1.4
```

### Additional Information

Related Discord Thread: https://discord.com/channels/842438759945601056/1046929728948408370/threads/1078666403630043157

**Comment by raine-works** [comment]
I am having this same issue after updating to @builder.io/qwik-city: 0.4.0.

**Comment by ngfelixl** [comment]
The issue seems to be related to the [**client-navigation.ts**](https://github.dev/BuilderIO/qwik/blob/7ee19bae822bd387bdfe2b37f7ceb5025e8cc8bb/packages/qwik-city/runtime/src/client-navigate.ts) and [**qwik-city-component.ts#L228**](https://github.dev/BuilderIO/qwik/blob/7ee19bae822bd387bdfe2b37f7ceb5025e8cc8bb/packages/qwik-city/runtime/src/qwik-city-component.tsx#L228). The `handleScroll` function does not execute neither. So the app does not scroll to top on route change.

**Comment by qq99** [comment]
This hit me the other day, I don't have anything to add, but commenting to get updates

**Comment by kldzj** [comment]
We're facing the same issue using with SSR and interestingly enough only once we enable encrypted traffic (over HTTPS).

**Comment by asplunds** [comment]
Experiencing this using the latest versions of qwik and qwik-city. Happens regardless of TLS. Works fine on dev but as soon as you deploy SSG it doesn't change URL on navigation.

**Comment by lbensaad** [comment]
I am having the same issue using version 0.21.0 even on dev behind nginx proxy using TLS. It works when I bypass the proxy and directly open http://localhost:5173  (Vite) but it does not work when I connect through nginx on httpS (that forwards to http://localhost:5173).

**Comment by ngfelixl** [comment]
I can confirm that compiling with `origin: 'http://localhost:8080'` works with `npx http-server ./dist` as @swwind mentioned. But still, using the `https://....` URL and deploy to Vercel does not work.

**Comment by swwind** [comment]
> But still, using the `https://....` URL and deploy to Vercel does not work.

Using the `https://...` URL and deploy to Netlify seems to work fine. I deployed a [static website on Netlify](https://zippy-baklava-ebedac.netlify.app/) and it seems to work.

**Comment by ngfelixl** [comment]
Ha amazing! Vercel redirects to `https://www.[...]` per default. That caused the issue. 

```
plugins: [
  staticAdapter({
    origin: 'http://www.exampledomain.com',
  }),
],
```

solves it!

**Comment by lbensaad** [comment]
I confirm that that solution works. But still does not work with pnpm dev behind nginx using SSL. 
I need SSL during dev and test because I am using secure and http-only cookies.

**Comment by swwind** [comment]
> I confirm that that solution works. But still does not work with pnpm dev behind nginx using SSL. I need SSL during dev and test because I am using secure and http-only cookies.

@lbensaad vite supports https out of box, you can have

```js
server: {
  https: {
    key: readFileSync('localhost-key.pem'),
    cert: readFileSync('localhost.pem'),
  },
}
```

in your `vite.config.ts` to enable https.

However, there still have some bugs in qwik here

https://github.com/BuilderIO/qwik/blob/c09b09cb3cd2b4043060f8d17ffeeca2bd3a80f4/packages/qwik/src/optimizer/src/plugins/vite-server.ts#L41

This logic does not handle the https situation correctly, which ends up `http://localhost` for our https dev server.

Same logic appears in node adapter which handles https server correctly here

https://github.com/BuilderIO/qwik/blob/c09b09cb3cd2b4043060f8d17ffeeca2bd3a80f4/packages/qwik-city/middleware/node/http.ts#L8-L24

Therefore, you can modify the `vite-server.ts#L41` into

```js
const domain = (req.socket.encrypted || req.connection.encrypted ? "https" : "http") + "://" + (req.headers[':authority'] ?? req.headers['host'] ?? "localhost");
```

to get your vite dev server work under https.

**Comment by lbensaad** [comment]
Thanks a lot @swwind, like that I get rid of nginx. I am using it mainly for CORS issues but I found that Vite also can proxy my api calls. 
The issue of URL not updating in the the browser is till there in dev mode when I use httpS. 
I will try fixing it using your PR #3322 
Thanks again

**Comment by Ghosterbeef** [comment]
I have the same problem on a dev server running through docker with nginx. The proposed solution does not help. I pointed to vite.config.ts origin and http://localhost:80 and http://frontend:3000 bc nginx works with these routes.

**Comment by lbensaad** [comment]
@Ghosterbeef it is worked for me. Now vite is serving at https://localhost:8080 and my api calls are proxied by vite to my backend. for https I applied the solution proposed by @swwind, but I hard coded the https in qwik optimizer waiting the team to accept the PR #3322

**Comment by Ghosterbeef** [comment]
@lbensaad i.e. the problem is nginx (if you don't consider ssl). I don't use ssl locally but am experiencing problems. Should I opt out of nginx?

**Comment by lbensaad** [comment]
@Ghosterbeef nginx is not the problem, i was using it and it was working without problem. The problem is that qwik does not handle https correctly. But know I found that I don't need nginx in dev, vite is enough, it supports https and proxy api request to backend: here is my vite config: 
``` export default defineConfig(() => {
  return {
    server: {
      port: 8080,
      https: {
        key: readFileSync('ssl/tls.key'),
        cert: readFileSync('ssl/tls.crt'),
      },
      proxy: {
        '/api': "http://localhost:50051"
      },
    },
  }
```

**Comment by Ghosterbeef** [comment]
@lbensaad the problem is that I don't use https locally but still run into this bug =)

**Comment by limotek** [comment]
Can confirm this also happens when deploying running with "Nodejs Express Server" and then run:
`npm run deploy`

Tried various reverse proxy solutions before I came across this report. Work 100% without SSL but happens as soon as I introduce SSL to the mix. Can confirm that @swwind solution work if I switch to SSG.

**Comment by astraldev** [comment]
Still occurs when deploying  with "Nodejs Express Server" and then running: 
npm run deploy

**Comment by denisyilmaz** [comment]
Same error here. It's working locally just fine, on a VPS with NodeJS 16 and the express adapter installed the routing is not updated.

Version:
    `"@builder.io/qwik": "0.24.0",`
    `"@builder.io/qwik-city": "0.7.0",`

**Comment by tzdesign** [comment]
It get's even wilder:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/3037096/228780593-6f4ee5e6-9016-470d-a3a4-4db159ac0c89.png">

I don't know what the qwik router is expecting, but it even blocks server$ POSTs.

Please keep in mind, that this is working 100% on preview and serving locally with express.
As soon as https is there it just stops working.

**Comment by tzdesign** [comment]
It's easy to test with ngrok:

```shell
yarn preview && ngrok http 4173
```

**Comment by tzdesign** [comment]
@lbensaad's pr is not solving this issue.

I don't understand this part in vite-server, on what level are the envs set?:
https://github.com/BuilderIO/qwik/blob/7fb20862c0bf1f4f7835cc6725686d5eb97d6a6f/packages/qwik/src/optimizer/src/plugins/vite-server.ts#L13-L22

I logged on middleware level and the getOrigin function in vite-server.ts is the origin of this error.

```ts
 console.log({
    PROTOCOL_HEADER,
    HOST_HEADER,
    headers: req.headers,
    socket: (req?.socket as any)?.encrypted,
    connection: (req?.connection as any)?.encrypted
  });
```
<img width="344" alt="image" src="https://user-images.githubusercontent.com/3037096/229095584-b6c2f7a4-6a4d-4546-916b-e615051d3782.png">

All empty so it will fallback on http all the time in production.

For everyone who needs a qwik fix, set the ORIGIN to your domain in production.

Does someone know why this was done with environment variables and did we all just miss something?

**Comment by tzdesign** [comment]
@manucorporat I read the whole vite-server.ts and I would say you are right, it's the devs job and a documentation topic.

Maybe you change the default express adapter to point this out as well?
We will have multiple Urls and it's only a protocol issue, as it finds the domain name, but cannot assume https from the headers.

So or so, we fixed it in docker for now.

**Comment by denisyilmaz** [comment]
do i understand this correctly that this would be the required change in the express adapter? or where does this need to be set? CORS is always messing with me...

```jsx
import { nodeServerAdapter } from '@builder.io/qwik-city/adapters/node-server/vite';
import { extendConfig } from '@builder.io/qwik-city/vite';
import baseConfig from '../../vite.config';

export default extendConfig(baseConfig, () => {
  return {
    build: {
      ssr: true,
      origin: 'https://www.example.com',
      rollupOptions: {
        input: ['src/entry.express.tsx', '@qwik-city-plan'],
      },
    },
    plugins: [nodeServerAdapter({
      name: 'express',
      ssg: {
        include: [],
        origin: 'https://www.example.com',
      }
    })],
  };
});
```

**Comment by limotek** [comment]
@denisyilmaz  (or anyone else that can help) can you please give more info if you changed anything else?  I  

1. created a fresh qwik app
2. add express adapter
3. change i.e. the <a href= of the flower to <Link href= (and import Link)
4. change the adapters/express/vite.config.ts to:

```jsx
import { nodeServerAdapter } from '@builder.io/qwik-city/adapters/node-server/vite';
import { extendConfig } from '@builder.io/qwik-city/vite';
import baseConfig from '../../vite.config';

export default extendConfig(baseConfig, () => {
  return {
    build: {
      ssr: true,
      origin: "https://mydomain.com",
      rollupOptions: {
        input: ['src/entry.express.tsx', '@qwik-city-plan'],
      },
    },
    plugins: [nodeServerAdapter({ 
      name: 'express',
      ssg: {
        include: [],
        origin: 'https://mydomain.com',
      }

    })],
  };
});
```

6. run
`npm run build`
7. run
`npm run serve`
8. I have nginx reverse proxy handling cert and forwarding to port 3000

If I click on the flower link, I get the flower page, but the url in the browser does not update.

What am I missing? Any assistance would be highly appreciated.

**Comment by adamdbradley** [comment]
Thanks for the repo case and comments. The previous problem was that the URL `origin` it was comparing to was the same one that the site was built with, during SSG. Which if it wasn't set, would be different than what's deployed.

Since the navigation check is on the client, I updated it so it made sure the location came directly from `window.location.href`, which would have the correct `origin` at runtime.

I also added more e2e tests to hopefully check any regressions earlier. Thanks again for the help!

https://github.com/BuilderIO/qwik/pull/3810
