### ISSUE TITLE
[🐞] Cannot build in v1.1.0 with Windows

### ISSUE THREAD

**Issue by rootEnginear** [BuilderIO/qwik#4147]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

Cannot build Qwik app even on fresh new application.

```
Could not resolve entry module "src/s_ebq0vfsfksk.js".
error during build:
RollupError: Could not resolve entry module "src/s_ebq0vfsfksk.js".
    at error (file:///D:/Desktop/qwik-app/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
    at ModuleLoader.loadEntryModule (file:///D:/Desktop/qwik-app/node_modules/rollup/dist/es/shared/node-entry.js:23959:20)
    at async Promise.all (index 0)
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-abdeqn?file=package.json

### Steps to reproduce

1. `npm create qwik@latest`
2. Select `Empty App (QwikCity)` (`Basic App (QwikCity)` is bugged too, other are not tested yet)
3. `cd qwik-app`
4. `yarn`
5. `yarn build`
6. Done

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 5.13 GB / 15.89 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @builder.io/qwik: ^1.1.0 => 1.1.0
    @builder.io/qwik-city: ^1.1.0 => 1.1.0
    undici: 5.22.0 => 5.22.0
    vite: 4.3.5 => 4.3.5
```

**Comment by irg1008** [comment]
Downgraded to windows, still same issue

**Comment by LuisCoderDev** [comment]
this issue still in 1.0.0 for me to

**Comment by markteekens** [comment]
same issue since yesterday

**Comment by manucorporat** [comment]
Should be fixed in 1.1.1, make sure to update qwik and qwik-city

**Comment by rootEnginear** [comment]
Worked for me! Thank you for your support. 🥳

**Comment by alimrb** [comment]
Still doesn't work for me, the same error.
npm run preview on just downloaded npm create latest, blank app or with demo example, with dependencies included.

With 1.0.0 and 1.1.1 both tried.
Windows 10

**Comment by irg1008** [comment]
@manucorporat Outstanding job, as always, thank you!

**Comment by alimrb** [comment]
> Still doesn't work for me, the same error. npm run preview on just downloaded npm create latest, blank app or with demo example, with dependencies included.
> 
> With 1.0.0 and 1.1.1 both tried. Windows 10

another machine, same situation works fine with 1.1.1

**Comment by alimrb** [comment]
> Still doesn't work for me, the same error. npm run preview on just downloaded npm create latest, blank app or with demo example, with dependencies included.
> 
> With 1.0.0 and 1.1.1 both tried. Windows 10

The problem was node js version. With Current version of node js, preview failed, I reinstalled the recommended version, it works.

**Comment by manucorporat** [comment]
which version of node failed? u got new other error?

**Comment by alimrb** [comment]
it seems node cdn is down but anyway from nodejs.org:

![image](https://github.com/BuilderIO/qwik/assets/13683303/c8d2196f-8132-4a68-b211-014d1035d4c5)
