### ISSUE TITLE
[BUG] Tailwind does currently not work in any starter

### ISSUE THREAD

**Issue by wtho** [BuilderIO/qwik#583]
### Qwik Version

0.0.24

### Operating System (or Browser)

Linux 5.18.1, Chromium 102.0.5005.61

### Node Version (if applicable)

18.3.0

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behaviour

Tailwind styles should be included in the bundle (dev-mode and production mode)

### Actual Behaviour

No tailwind styles are applied.

### Additional Information

Reproduction: 
* use any starter and tick the tailwind option during creation
* set a tailwind style in any component, e. g. `bg-red-500` on any div
* start build/dev mode

**Comment by manucorporat** [comment]
Fixed by https://github.com/BuilderIO/qwik/commit/8c4e554686cd35e00e197a75dfaa0322b7e54c6e

**Comment by wtho** [comment]
@manucorporat When trying out qwik v`0.0.25`, it still does not work with tailwind (or any CSS changes in `src/global.css`)

Can you please check again and reopen the issue?

Maybe I find some time to compare the starters to the documentation website.
